#!/usr/bin/env bash
# Print 8 times Best School with While Loop
# but for the 4th display bad luck
# the 8th displays good luck

i=1
while [ $i -le 10 ]
do
    if [ "$i" -eq 4 ]
    then
	echo "bad luck"
    elif [ "$i" -eq 8 ]
    then
	echo "good luck"
    else
	echo "Best School"
    fi

    ((i++))
done
